DefaultContentLanguage = "de"
MetaDataFormat = "yaml"
SectionPagesMenu = "main"
baseURL = "/"
copyright = "River Side Bowling GmbH"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "de-de"
theme = "ananke"
title = "River Side Bowling"

[params]
background_color_class = "bg-black"
description = ""
facebook = "https://www.facebook.com/RiverSideBowling/"
favicon = ""
featured_image = ""
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
slack = ""
stackoverflow = ""
twitter = ""
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
