DefaultContentLanguage = "de"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "/"
copyright = "River Side Bowling GmbH"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "de-de"
theme = "ananke"
themesDir = "themes"
title = "River Side Bowling"
[params]
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
facebook = "https://www.facebook.com/RiverSideBowling/"
favicon = ""
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
recent_posts_number = 2
slack = ""
stackoverflow = ""
twitter = ""
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
